// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscoverReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverReply) Reset()         { *m = DiscoverReply{} }
func (m *DiscoverReply) String() string { return proto.CompactTextString(m) }
func (*DiscoverReply) ProtoMessage()    {}
func (*DiscoverReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *DiscoverReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverReply.Unmarshal(m, b)
}
func (m *DiscoverReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverReply.Marshal(b, m, deterministic)
}
func (m *DiscoverReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverReply.Merge(m, src)
}
func (m *DiscoverReply) XXX_Size() int {
	return xxx_messageInfo_DiscoverReply.Size(m)
}
func (m *DiscoverReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverReply.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverReply proto.InternalMessageInfo

type EmptyReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyReply) Reset()         { *m = EmptyReply{} }
func (m *EmptyReply) String() string { return proto.CompactTextString(m) }
func (*EmptyReply) ProtoMessage()    {}
func (*EmptyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *EmptyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyReply.Unmarshal(m, b)
}
func (m *EmptyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyReply.Marshal(b, m, deterministic)
}
func (m *EmptyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyReply.Merge(m, src)
}
func (m *EmptyReply) XXX_Size() int {
	return xxx_messageInfo_EmptyReply.Size(m)
}
func (m *EmptyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyReply.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyReply proto.InternalMessageInfo

type FetchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

type ClientConfig struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Queues               []*QueueConfig `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ClientConfig) Reset()         { *m = ClientConfig{} }
func (m *ClientConfig) String() string { return proto.CompactTextString(m) }
func (*ClientConfig) ProtoMessage()    {}
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ClientConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConfig.Unmarshal(m, b)
}
func (m *ClientConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConfig.Marshal(b, m, deterministic)
}
func (m *ClientConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConfig.Merge(m, src)
}
func (m *ClientConfig) XXX_Size() int {
	return xxx_messageInfo_ClientConfig.Size(m)
}
func (m *ClientConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConfig proto.InternalMessageInfo

func (m *ClientConfig) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClientConfig) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ClientConfig) GetQueues() []*QueueConfig {
	if m != nil {
		return m.Queues
	}
	return nil
}

type QueueConfig struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority             int32    `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueConfig) Reset()         { *m = QueueConfig{} }
func (m *QueueConfig) String() string { return proto.CompactTextString(m) }
func (*QueueConfig) ProtoMessage()    {}
func (*QueueConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *QueueConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueConfig.Unmarshal(m, b)
}
func (m *QueueConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueConfig.Marshal(b, m, deterministic)
}
func (m *QueueConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueConfig.Merge(m, src)
}
func (m *QueueConfig) XXX_Size() int {
	return xxx_messageInfo_QueueConfig.Size(m)
}
func (m *QueueConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueConfig.DiscardUnknown(m)
}

var xxx_messageInfo_QueueConfig proto.InternalMessageInfo

func (m *QueueConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QueueConfig) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type Ack struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type Execution struct {
	Expiry               int64    `protobuf:"varint,1,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (m *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(m, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type JobPayload struct {
	Jid                  string            `protobuf:"bytes,1,opt,name=jid,proto3" json:"jid,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Args                 map[string]*Param `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Retry                int32             `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"`
	EnqueueAt            int64             `protobuf:"varint,6,opt,name=enqueue_at,json=enqueueAt,proto3" json:"enqueue_at,omitempty"`
	ReserveFor           int64             `protobuf:"varint,7,opt,name=reserve_for,json=reserveFor,proto3" json:"reserve_for,omitempty"`
	Queue                string            `protobuf:"bytes,8,opt,name=queue,proto3" json:"queue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *JobPayload) Reset()         { *m = JobPayload{} }
func (m *JobPayload) String() string { return proto.CompactTextString(m) }
func (*JobPayload) ProtoMessage()    {}
func (*JobPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *JobPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobPayload.Unmarshal(m, b)
}
func (m *JobPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobPayload.Marshal(b, m, deterministic)
}
func (m *JobPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobPayload.Merge(m, src)
}
func (m *JobPayload) XXX_Size() int {
	return xxx_messageInfo_JobPayload.Size(m)
}
func (m *JobPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_JobPayload.DiscardUnknown(m)
}

var xxx_messageInfo_JobPayload proto.InternalMessageInfo

func (m *JobPayload) GetJid() string {
	if m != nil {
		return m.Jid
	}
	return ""
}

func (m *JobPayload) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobPayload) GetArgs() map[string]*Param {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *JobPayload) GetRetry() int32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *JobPayload) GetEnqueueAt() int64 {
	if m != nil {
		return m.EnqueueAt
	}
	return 0
}

func (m *JobPayload) GetReserveFor() int64 {
	if m != nil {
		return m.ReserveFor
	}
	return 0
}

func (m *JobPayload) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type Param struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Param) Reset()         { *m = Param{} }
func (m *Param) String() string { return proto.CompactTextString(m) }
func (*Param) ProtoMessage()    {}
func (*Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Param.Unmarshal(m, b)
}
func (m *Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Param.Marshal(b, m, deterministic)
}
func (m *Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Param.Merge(m, src)
}
func (m *Param) XXX_Size() int {
	return xxx_messageInfo_Param.Size(m)
}
func (m *Param) XXX_DiscardUnknown() {
	xxx_messageInfo_Param.DiscardUnknown(m)
}

var xxx_messageInfo_Param proto.InternalMessageInfo

func (m *Param) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Param) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Queue struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Queue) Reset()         { *m = Queue{} }
func (m *Queue) String() string { return proto.CompactTextString(m) }
func (*Queue) ProtoMessage()    {}
func (*Queue) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *Queue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Queue.Unmarshal(m, b)
}
func (m *Queue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Queue.Marshal(b, m, deterministic)
}
func (m *Queue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Queue.Merge(m, src)
}
func (m *Queue) XXX_Size() int {
	return xxx_messageInfo_Queue.Size(m)
}
func (m *Queue) XXX_DiscardUnknown() {
	xxx_messageInfo_Queue.DiscardUnknown(m)
}

var xxx_messageInfo_Queue proto.InternalMessageInfo

func (m *Queue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FailPayload struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	ErrorType            string   `protobuf:"bytes,3,opt,name=errorType,proto3" json:"errorType,omitempty"`
	Retry                int32    `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"`
	Backtrace            []string `protobuf:"bytes,5,rep,name=backtrace,proto3" json:"backtrace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailPayload) Reset()         { *m = FailPayload{} }
func (m *FailPayload) String() string { return proto.CompactTextString(m) }
func (*FailPayload) ProtoMessage()    {}
func (*FailPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{11}
}

func (m *FailPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailPayload.Unmarshal(m, b)
}
func (m *FailPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailPayload.Marshal(b, m, deterministic)
}
func (m *FailPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailPayload.Merge(m, src)
}
func (m *FailPayload) XXX_Size() int {
	return xxx_messageInfo_FailPayload.Size(m)
}
func (m *FailPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_FailPayload.DiscardUnknown(m)
}

var xxx_messageInfo_FailPayload proto.InternalMessageInfo

func (m *FailPayload) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FailPayload) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *FailPayload) GetErrorType() string {
	if m != nil {
		return m.ErrorType
	}
	return ""
}

func (m *FailPayload) GetRetry() int32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *FailPayload) GetBacktrace() []string {
	if m != nil {
		return m.Backtrace
	}
	return nil
}

type Ping struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{12}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Pong struct {
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pong) Reset()         { *m = Pong{} }
func (m *Pong) String() string { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()    {}
func (*Pong) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{13}
}

func (m *Pong) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pong.Unmarshal(m, b)
}
func (m *Pong) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pong.Marshal(b, m, deterministic)
}
func (m *Pong) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pong.Merge(m, src)
}
func (m *Pong) XXX_Size() int {
	return xxx_messageInfo_Pong.Size(m)
}
func (m *Pong) XXX_DiscardUnknown() {
	xxx_messageInfo_Pong.DiscardUnknown(m)
}

var xxx_messageInfo_Pong proto.InternalMessageInfo

func (m *Pong) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscoverReply)(nil), "protobuf.DiscoverReply")
	proto.RegisterType((*EmptyReply)(nil), "protobuf.EmptyReply")
	proto.RegisterType((*FetchRequest)(nil), "protobuf.FetchRequest")
	proto.RegisterType((*ClientConfig)(nil), "protobuf.ClientConfig")
	proto.RegisterType((*QueueConfig)(nil), "protobuf.QueueConfig")
	proto.RegisterType((*Ack)(nil), "protobuf.Ack")
	proto.RegisterType((*Execution)(nil), "protobuf.Execution")
	proto.RegisterType((*JobPayload)(nil), "protobuf.JobPayload")
	proto.RegisterMapType((map[string]*Param)(nil), "protobuf.JobPayload.ArgsEntry")
	proto.RegisterType((*Param)(nil), "protobuf.Param")
	proto.RegisterType((*Queue)(nil), "protobuf.Queue")
	proto.RegisterType((*Job)(nil), "protobuf.Job")
	proto.RegisterType((*FailPayload)(nil), "protobuf.FailPayload")
	proto.RegisterType((*Ping)(nil), "protobuf.Ping")
	proto.RegisterType((*Pong)(nil), "protobuf.Pong")
}

func init() {
	proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7)
}

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x10, 0x8d, 0xed, 0x38, 0xc4, 0x93, 0x00, 0x9f, 0x56, 0xc0, 0x67, 0xa5, 0xb4, 0x8d, 0xb6, 0xaa,
	0xc4, 0x4d, 0x23, 0x48, 0x5b, 0xa9, 0x6a, 0xc5, 0x45, 0xa0, 0x20, 0x84, 0x54, 0x89, 0xba, 0xbd,
	0x47, 0x1b, 0x67, 0x70, 0xb7, 0x4e, 0xbc, 0x66, 0xbd, 0xa6, 0xf8, 0x39, 0x7a, 0xdb, 0xc7, 0xea,
	0x03, 0x55, 0x5e, 0xff, 0x06, 0xc1, 0x55, 0x76, 0x8e, 0xcf, 0xce, 0x9c, 0xd9, 0x33, 0x13, 0x18,
	0x26, 0x28, 0xef, 0x50, 0x4e, 0x62, 0x29, 0x94, 0x20, 0x7d, 0xfd, 0x33, 0x4f, 0x6f, 0xe8, 0x36,
	0x6c, 0x7e, 0xe6, 0x89, 0x2f, 0xee, 0x50, 0x7a, 0x18, 0x2f, 0x33, 0x3a, 0x04, 0x38, 0x5b, 0xc5,
	0x2a, 0x2b, 0xa2, 0x2d, 0x18, 0x9e, 0xa3, 0xf2, 0x7f, 0x78, 0x78, 0x9b, 0x62, 0xa2, 0x28, 0x83,
	0xe1, 0xe9, 0x92, 0x63, 0xa4, 0x4e, 0x45, 0x74, 0xc3, 0x03, 0xb2, 0x05, 0x26, 0x5f, 0xb8, 0xc6,
	0xd8, 0x38, 0x70, 0x3c, 0x93, 0x2f, 0x08, 0x81, 0xae, 0xca, 0x62, 0x74, 0x4d, 0x8d, 0xe8, 0x33,
	0x79, 0x03, 0xbd, 0xdb, 0x14, 0x53, 0x4c, 0x5c, 0x6b, 0x6c, 0x1d, 0x0c, 0xa6, 0xbb, 0x93, 0xaa,
	0xfa, 0xe4, 0x6b, 0x8e, 0x17, 0xa9, 0xbc, 0x92, 0x44, 0x8f, 0x61, 0xd0, 0x82, 0xf3, 0x8c, 0x11,
	0x5b, 0x61, 0x59, 0x43, 0x9f, 0xc9, 0x08, 0xfa, 0xb1, 0xe4, 0x42, 0x72, 0x95, 0xe9, 0x4a, 0xb6,
	0x57, 0xc7, 0x74, 0x17, 0xac, 0x99, 0x1f, 0xe6, 0xc2, 0x44, 0xa8, 0x2f, 0xf5, 0x3d, 0x53, 0x84,
	0xf4, 0x15, 0x38, 0x67, 0xf7, 0xe8, 0xa7, 0x8a, 0x8b, 0x88, 0xec, 0x41, 0x0f, 0xef, 0x63, 0x2e,
	0x33, 0x4d, 0xb0, 0xbc, 0x32, 0xa2, 0x7f, 0x4c, 0x80, 0x4b, 0x31, 0xbf, 0x62, 0xd9, 0x52, 0xb0,
	0x05, 0xf9, 0x0f, 0xac, 0x9f, 0x75, 0x77, 0xf9, 0xb1, 0x16, 0x63, 0xb6, 0xc4, 0x4c, 0xa1, 0xcb,
	0x64, 0x50, 0x35, 0xf7, 0xa2, 0x69, 0xae, 0xc9, 0x34, 0x99, 0xc9, 0x20, 0x39, 0x8b, 0x94, 0xcc,
	0x3c, 0xcd, 0x25, 0x3b, 0x60, 0x4b, 0x54, 0x32, 0x73, 0xbb, 0x5a, 0x7d, 0x11, 0x90, 0xe7, 0x00,
	0x18, 0xe9, 0x57, 0xb8, 0x66, 0xca, 0xed, 0x69, 0x69, 0x4e, 0x89, 0xcc, 0x14, 0x79, 0x09, 0x03,
	0x89, 0xda, 0xc6, 0xeb, 0x1b, 0x21, 0xdd, 0x0d, 0xfd, 0x1d, 0x4a, 0xe8, 0x5c, 0xc8, 0x3c, 0xab,
	0xe6, 0xba, 0x7d, 0x2d, 0xaf, 0x08, 0x46, 0x17, 0xe0, 0xd4, 0xe5, 0xf3, 0x96, 0x42, 0xcc, 0xaa,
	0x96, 0x42, 0xcc, 0xc8, 0x6b, 0xb0, 0xef, 0xd8, 0x32, 0x2d, 0x7a, 0x1a, 0x4c, 0xb7, 0x1b, 0xfd,
	0x57, 0x4c, 0xb2, 0x95, 0x57, 0x7c, 0xfd, 0x68, 0x7e, 0x30, 0xe8, 0x11, 0xd8, 0x1a, 0xab, 0x5d,
	0x36, 0x5a, 0x2e, 0xef, 0xb4, 0xf3, 0x0c, 0xcb, 0x6b, 0xf4, 0x19, 0xd8, 0xda, 0xcc, 0xc7, 0x6c,
	0xcc, 0xad, 0xba, 0x14, 0xf3, 0x87, 0x33, 0x44, 0x7f, 0x1b, 0x30, 0x38, 0x67, 0x7c, 0x59, 0xd9,
	0xf0, 0x70, 0xc6, 0x28, 0x0c, 0x51, 0x4a, 0x21, 0xbf, 0x60, 0x92, 0xb0, 0xa0, 0x32, 0x63, 0x0d,
	0x23, 0xfb, 0xe0, 0xe8, 0xf8, 0x7b, 0x2e, 0xd3, 0xd2, 0x84, 0x06, 0x78, 0xe2, 0xf9, 0xf7, 0xc1,
	0x99, 0x33, 0x3f, 0x54, 0x92, 0xf9, 0xe8, 0xda, 0x63, 0x2b, 0xbf, 0x53, 0x03, 0x74, 0x0c, 0xdd,
	0x2b, 0x1e, 0x05, 0xc4, 0x85, 0x8d, 0x55, 0x59, 0xb8, 0x90, 0x54, 0x85, 0x9a, 0x21, 0xd6, 0x19,
	0xe6, 0x1a, 0x63, 0xfa, 0xd7, 0x84, 0xee, 0x37, 0x1e, 0x08, 0x72, 0x0c, 0xfd, 0x6a, 0xeb, 0xc8,
	0x5e, 0xf3, 0xe2, 0xed, 0xd5, 0x1a, 0xfd, 0xdf, 0xe0, 0xeb, 0x1b, 0xda, 0x21, 0xef, 0xc0, 0x39,
	0x91, 0x82, 0x2d, 0x4e, 0x59, 0xa2, 0xc8, 0xce, 0x63, 0x13, 0x37, 0xda, 0x6c, 0xd0, 0x99, 0x1f,
	0xd2, 0xce, 0x81, 0x41, 0x0e, 0xc1, 0xd6, 0xbb, 0x4c, 0xb6, 0x1f, 0x2c, 0xe0, 0xe8, 0xd1, 0x14,
	0xb4, 0x43, 0x3e, 0xc1, 0x60, 0xe6, 0x87, 0x91, 0xf8, 0xb5, 0xc4, 0x45, 0x80, 0x4f, 0x54, 0x6a,
	0xa1, 0xad, 0x3f, 0x8e, 0x0e, 0x79, 0x0f, 0xdd, 0xdc, 0x45, 0xd2, 0x5a, 0xf7, 0x96, 0xab, 0x4f,
	0x5e, 0x3b, 0x02, 0xe7, 0x02, 0x99, 0x54, 0x27, 0xc8, 0x14, 0xd9, 0x6a, 0x4d, 0x23, 0x8f, 0x82,
	0x51, 0x3b, 0x16, 0x51, 0x90, 0xb7, 0x75, 0x68, 0xcc, 0x7b, 0x1a, 0x7c, 0xfb, 0x2f, 0x00, 0x00,
	0xff, 0xff, 0x50, 0x6b, 0x7f, 0x1e, 0xe4, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SigoClient is the client API for Sigo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SigoClient interface {
	Discover(ctx context.Context, in *ClientConfig, opts ...grpc.CallOption) (*DiscoverReply, error)
	BroadCast(ctx context.Context, opts ...grpc.CallOption) (Sigo_BroadCastClient, error)
	Fetch(ctx context.Context, in *Queue, opts ...grpc.CallOption) (*JobPayload, error)
	Acknowledge(ctx context.Context, in *JobPayload, opts ...grpc.CallOption) (*EmptyReply, error)
	Fail(ctx context.Context, in *FailPayload, opts ...grpc.CallOption) (*EmptyReply, error)
	HeartBeat(ctx context.Context, opts ...grpc.CallOption) (Sigo_HeartBeatClient, error)
}

type sigoClient struct {
	cc grpc.ClientConnInterface
}

func NewSigoClient(cc grpc.ClientConnInterface) SigoClient {
	return &sigoClient{cc}
}

func (c *sigoClient) Discover(ctx context.Context, in *ClientConfig, opts ...grpc.CallOption) (*DiscoverReply, error) {
	out := new(DiscoverReply)
	err := c.cc.Invoke(ctx, "/protobuf.Sigo/Discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigoClient) BroadCast(ctx context.Context, opts ...grpc.CallOption) (Sigo_BroadCastClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sigo_serviceDesc.Streams[0], "/protobuf.Sigo/BroadCast", opts...)
	if err != nil {
		return nil, err
	}
	x := &sigoBroadCastClient{stream}
	return x, nil
}

type Sigo_BroadCastClient interface {
	Send(*JobPayload) error
	CloseAndRecv() (*Ack, error)
	grpc.ClientStream
}

type sigoBroadCastClient struct {
	grpc.ClientStream
}

func (x *sigoBroadCastClient) Send(m *JobPayload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sigoBroadCastClient) CloseAndRecv() (*Ack, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sigoClient) Fetch(ctx context.Context, in *Queue, opts ...grpc.CallOption) (*JobPayload, error) {
	out := new(JobPayload)
	err := c.cc.Invoke(ctx, "/protobuf.Sigo/Fetch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigoClient) Acknowledge(ctx context.Context, in *JobPayload, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/protobuf.Sigo/Acknowledge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigoClient) Fail(ctx context.Context, in *FailPayload, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, "/protobuf.Sigo/Fail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sigoClient) HeartBeat(ctx context.Context, opts ...grpc.CallOption) (Sigo_HeartBeatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sigo_serviceDesc.Streams[1], "/protobuf.Sigo/HeartBeat", opts...)
	if err != nil {
		return nil, err
	}
	x := &sigoHeartBeatClient{stream}
	return x, nil
}

type Sigo_HeartBeatClient interface {
	Send(*Ping) error
	Recv() (*Pong, error)
	grpc.ClientStream
}

type sigoHeartBeatClient struct {
	grpc.ClientStream
}

func (x *sigoHeartBeatClient) Send(m *Ping) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sigoHeartBeatClient) Recv() (*Pong, error) {
	m := new(Pong)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SigoServer is the server API for Sigo service.
type SigoServer interface {
	Discover(context.Context, *ClientConfig) (*DiscoverReply, error)
	BroadCast(Sigo_BroadCastServer) error
	Fetch(context.Context, *Queue) (*JobPayload, error)
	Acknowledge(context.Context, *JobPayload) (*EmptyReply, error)
	Fail(context.Context, *FailPayload) (*EmptyReply, error)
	HeartBeat(Sigo_HeartBeatServer) error
}

// UnimplementedSigoServer can be embedded to have forward compatible implementations.
type UnimplementedSigoServer struct {
}

func (*UnimplementedSigoServer) Discover(ctx context.Context, req *ClientConfig) (*DiscoverReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (*UnimplementedSigoServer) BroadCast(srv Sigo_BroadCastServer) error {
	return status.Errorf(codes.Unimplemented, "method BroadCast not implemented")
}
func (*UnimplementedSigoServer) Fetch(ctx context.Context, req *Queue) (*JobPayload, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (*UnimplementedSigoServer) Acknowledge(ctx context.Context, req *JobPayload) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Acknowledge not implemented")
}
func (*UnimplementedSigoServer) Fail(ctx context.Context, req *FailPayload) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fail not implemented")
}
func (*UnimplementedSigoServer) HeartBeat(srv Sigo_HeartBeatServer) error {
	return status.Errorf(codes.Unimplemented, "method HeartBeat not implemented")
}

func RegisterSigoServer(s *grpc.Server, srv SigoServer) {
	s.RegisterService(&_Sigo_serviceDesc, srv)
}

func _Sigo_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigoServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Sigo/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigoServer).Discover(ctx, req.(*ClientConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sigo_BroadCast_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SigoServer).BroadCast(&sigoBroadCastServer{stream})
}

type Sigo_BroadCastServer interface {
	SendAndClose(*Ack) error
	Recv() (*JobPayload, error)
	grpc.ServerStream
}

type sigoBroadCastServer struct {
	grpc.ServerStream
}

func (x *sigoBroadCastServer) SendAndClose(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sigoBroadCastServer) Recv() (*JobPayload, error) {
	m := new(JobPayload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Sigo_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Queue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigoServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Sigo/Fetch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigoServer).Fetch(ctx, req.(*Queue))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sigo_Acknowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigoServer).Acknowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Sigo/Acknowledge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigoServer).Acknowledge(ctx, req.(*JobPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sigo_Fail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigoServer).Fail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Sigo/Fail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigoServer).Fail(ctx, req.(*FailPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sigo_HeartBeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SigoServer).HeartBeat(&sigoHeartBeatServer{stream})
}

type Sigo_HeartBeatServer interface {
	Send(*Pong) error
	Recv() (*Ping, error)
	grpc.ServerStream
}

type sigoHeartBeatServer struct {
	grpc.ServerStream
}

func (x *sigoHeartBeatServer) Send(m *Pong) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sigoHeartBeatServer) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sigo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Sigo",
	HandlerType: (*SigoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Discover",
			Handler:    _Sigo_Discover_Handler,
		},
		{
			MethodName: "Fetch",
			Handler:    _Sigo_Fetch_Handler,
		},
		{
			MethodName: "Acknowledge",
			Handler:    _Sigo_Acknowledge_Handler,
		},
		{
			MethodName: "Fail",
			Handler:    _Sigo_Fail_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BroadCast",
			Handler:       _Sigo_BroadCast_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "HeartBeat",
			Handler:       _Sigo_HeartBeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "server.proto",
}
